"""add seller to gem model

Revision ID: 0260cfdb3c49
Revises: 12b944b94399
Create Date: 2024-10-09 21:51:24.079135

"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0260cfdb3c49'
down_revision: Union[str, None] = '12b944b94399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gem', 'user', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gem', type_='foreignkey')
    op.drop_column('gem', 'seller_id')
    # ### end Alembic commands ###
